### ISSUE TITLE
Help wanted

### ISSUE THREAD

**Issue by unional** [typed-typings/npm-lodash#1]
:rose:

**Comment by demurgos** [comment]
I took a look at the lodash file today and it seems like it would benefit some work. I'll try to review it during the next days.

What's your opinion on changes introducing stricter typings ? It won't break any builds but may cause some warnings when the compiler can't infer everything.
I think that a stricter declaration (while still respecting the API) is better, but it may cause some refactoring by the consumer (I'm not sure if it will really happen here, but it's a broader question).

**Comment by unional** [comment]
I think it really depends on how extensive the types are begin used. So it really depends on the type of package.

IMO `lodash` would be fine, as you won't use any types from `lodash` in your own code.

**Comment by demurgos** [comment]
Ok, thank you

**Comment by unional** [comment]
> Ok, thank you

Just to clarify, I agree that it should be stricter as you suggest. :smile:

**Comment by KiaraGrouwstra** [comment]
If it helps, feel free to take some inspiration from the [ramda typings](https://github.com/types/npm-ramda/). Currying and method chaining aside, I think we've shared many of the same challenges -- many functions between the two libraries are shared anyway.
