### ISSUE TITLE
Definitions missing

### ISSUE THREAD

**Issue by stevehipwell** [typed-typings/npm-lodash#11]
This typings file is not as up to date as the one on [DT](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/lodash/lodash.d.ts).

As an example compare _flatMap_, which is a dummy here but fully defined on DT, I'm sure there are others.

**Comment by demurgos** [comment]
I'm really glad that you opened an issue about this.
There are effectively a few more missing functions or signatures that could be updated to better match the expected type. I almost started a full review of lodash a few weeks ago but I had to delay it. 

If you have some time, how about submitting a PR ? (or at least a list of definitions so someone could just import these definitions)

We are still in the transition from DT to typings so it's normal that people still contribute to the DT repo, but maybe we should redirect them here ?
