### ISSUE TITLE
test fail related to blue-tape

### ISSUE THREAD

**Issue by unional** [typed-typings/npm-lodash#3]
``` sh
> typings bundle . -o bundle.d.ts

----------------------------------
⨯ Unable to compile TypeScript

typings/main/definitions/blue-tape/blue-tape.d.ts (9,26): Cannot find module 'stream'. (2307)
```

@blakeembrey , I'll add tests to `npm-blue-tape`. Maybe 2nd resolution fails (`npm-lodash` => `npm-blue-tape` => `npm-tape`)?

**Comment by unional** [comment]
This might be closely related to https://github.com/typings/typings/issues/281?

**Comment by princjef** [comment]
I have also run into this issue when i have dependencies that themselves have other ambient dependencies. For instance, if you do typings install --ambient express, it will not install any of its dependencies, such as node or serve-static. The only solution I've found is to do `typings install --ambient --save <package>` on whatever dependencies it can't resolve

**Comment by blakeembrey** [comment]
@unional  `typings install node -SA`. Need better logging for the "ambient modules" that are expected during installation.

**Comment by unional** [comment]
`-SD` in this case. :)

**Comment by blakeembrey** [comment]
Actually, `-DA` for `--save-dev --ambient` :smile:

**Comment by unional** [comment]
OH YEAH! :stuck_out_tongue_closed_eyes:

**Comment by unional** [comment]
Also thanks @princjef for pointing it out.
