### ISSUE TITLE
How to test typings

### ISSUE THREAD

**Issue by demurgos** [typed-typings/npm-lodash#8]
Hi,
I wanted to work on these typings but I stumbled upon this simple error: how can I quickly test the syntax and validity of my typings ?

Is running `npm run build+test` enough ? (I had some problems -lodash not found- at first but it seems to work now).
How should the tests work ? Is the point for them to compile without emitting any warning ? (Currently, I only see a runtime test)

**Comment by unional** [comment]
Yes `build+test` or just `watch`

Writing runtime times are needed as JavaScript is not typed to begin with. 

You only need to write runtime tests that ensure the signature is correct. 
Checkout `generator-typings`, there is an issue related to this topic. 

The best is to reuse tests from the source, but that still needs some work.
